# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RFID_mode(object):
    def setupUi(self, RFID_mode):
        RFID_mode.setObjectName("RFID_mode")
        RFID_mode.resize(1139, 810)
        self.centralwidget = QtWidgets.QWidget(RFID_mode)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 100, 901, 521))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 70, 861, 431))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(40, 0, 301, 361))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_s = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_s.setGeometry(QtCore.QRect(10, 60, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_s.setFont(font)
        self.lineEdit_s.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_s.setObjectName("lineEdit_s")
        self.lineEdit_l = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_l.setGeometry(QtCore.QRect(10, 130, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_l.setFont(font)
        self.lineEdit_l.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_l.setObjectName("lineEdit_l")
        self.lineEdit_t = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_t.setGeometry(QtCore.QRect(10, 200, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_t.setFont(font)
        self.lineEdit_t.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_t.setObjectName("lineEdit_t")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(60, 10, 191, 31))
        self.label_3.setStyleSheet("font: 18pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 221, 31))
        self.label_4.setStyleSheet("font: 18pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.pushButton_import = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_import.setGeometry(QtCore.QRect(30, 310, 41, 41))
        self.pushButton_import.setStyleSheet("border-image: url(:/images/images/imput.png);")
        self.pushButton_import.setText("")
        self.pushButton_import.setObjectName("pushButton_import")
        self.pushButton_update = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_update.setGeometry(QtCore.QRect(90, 310, 41, 41))
        self.pushButton_update.setStyleSheet("border-image: url(:/images/images/update.png);\n"
"border:none;")
        self.pushButton_update.setText("")
        self.pushButton_update.setObjectName("pushButton_update")
        self.pushButton_close = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_close.setGeometry(QtCore.QRect(210, 310, 41, 41))
        self.pushButton_close.setStyleSheet("border-image: url(:/images/images/clear.png);\n"
"border:none;")
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_look = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_look.setGeometry(QtCore.QRect(150, 310, 41, 41))
        self.pushButton_look.setStyleSheet("border-image: url(:/images/images/look.png);")
        self.pushButton_look.setText("")
        self.pushButton_look.setObjectName("pushButton_look")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 370, 281, 51))
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    font: 18pt \"Arial\";\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#pushButton_2:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#pushButton_2:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setGeometry(QtCore.QRect(350, 0, 511, 361))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_process = QtWidgets.QLabel(self.frame_3)
        self.label_process.setGeometry(QtCore.QRect(170, 10, 191, 31))
        self.label_process.setStyleSheet("font: 18pt \"Arial\";")
        self.label_process.setObjectName("label_process")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_3)
        self.graphicsView.setGeometry(QtCore.QRect(10, 60, 491, 291))
        self.graphicsView.setStyleSheet("\n"
"border:3px solid rgb(0,0,0);")
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 370, 281, 51))
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"    font: 18pt \"Arial\";\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#pushButton_3:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#pushButton_3:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.page)
        self.textBrowser.setGeometry(QtCore.QRect(370, 370, 171, 51))
        self.textBrowser.setStyleSheet("border:1px solid rgb(0,0,0);")
        self.textBrowser.setObjectName("textBrowser")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 50, 841, 211))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(190, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_11.setPlaceholderText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(20, 50, 131, 31))
        self.label_8.setStyleSheet("font: 18pt \"Arial\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(20, 90, 131, 31))
        self.label_9.setStyleSheet("font: 18pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(20, 130, 121, 31))
        self.label_10.setStyleSheet("font: 18pt \"Arial\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(20, 170, 121, 31))
        self.label_11.setStyleSheet("font: 18pt \"Arial\";")
        self.label_11.setObjectName("label_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_12.setGeometry(QtCore.QRect(610, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_12.setPlaceholderText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_13.setGeometry(QtCore.QRect(400, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_13.setPlaceholderText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_14.setGeometry(QtCore.QRect(190, 90, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_14.setPlaceholderText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_15.setGeometry(QtCore.QRect(400, 90, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_15.setPlaceholderText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_16.setGeometry(QtCore.QRect(610, 90, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_16.setPlaceholderText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_17.setGeometry(QtCore.QRect(190, 130, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_17.setPlaceholderText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_18.setGeometry(QtCore.QRect(400, 130, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_18.setPlaceholderText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_19.setGeometry(QtCore.QRect(610, 130, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_19.setPlaceholderText("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_20.setGeometry(QtCore.QRect(190, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_20.setPlaceholderText("")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_21.setGeometry(QtCore.QRect(400, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_21.setPlaceholderText("")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_22.setGeometry(QtCore.QRect(610, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_22.setPlaceholderText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(190, 10, 141, 31))
        self.label_12.setStyleSheet("font: 16pt \"Arial\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(410, 10, 141, 31))
        self.label_13.setStyleSheet("font: 16pt \"Arial\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(600, 10, 171, 31))
        self.label_14.setStyleSheet("font: 16pt \"Arial\";")
        self.label_14.setObjectName("label_14")
        self.frame_5 = QtWidgets.QFrame(self.page_2)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 71, 61))
        self.frame_5.setStyleSheet("border-image: url(:/images/images/data.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 370, 281, 51))
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
"    font: 18pt \"Arial\";\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#pushButton_5:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#pushButton_5:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_import_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_import_2.setGeometry(QtCore.QRect(20, 280, 51, 51))
        self.pushButton_import_2.setStyleSheet("border-image: url(:/images/images/right.png);")
        self.pushButton_import_2.setText("")
        self.pushButton_import_2.setObjectName("pushButton_import_2")
        self.pushButton_import_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_import_3.setGeometry(QtCore.QRect(190, 290, 31, 31))
        self.pushButton_import_3.setStyleSheet("border-image: url(:/images/images/del.png);")
        self.pushButton_import_3.setText("")
        self.pushButton_import_3.setObjectName("pushButton_import_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(540, 280, 261, 51))
        self.textBrowser_2.setStyleSheet("border:1px solid rgb(0,0,0);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(330, 290, 201, 31))
        self.label_15.setStyleSheet("font: 18pt \"Arial\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setGeometry(QtCore.QRect(80, 290, 61, 31))
        self.label_16.setStyleSheet("font: 18pt \"Arial\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_2)
        self.label_17.setGeometry(QtCore.QRect(230, 290, 61, 31))
        self.label_17.setStyleSheet("font: 18pt \"Arial\";")
        self.label_17.setObjectName("label_17")
        self.stackedWidget.addWidget(self.page_2)
        self.close = QtWidgets.QPushButton(self.frame)
        self.close.setGeometry(QtCore.QRect(850, 20, 31, 31))
        self.close.setStyleSheet("image: url(:/images/images/cha.png);\n"
"border:none;")
        self.close.setText("")
        self.close.setObjectName("close")
        self.tab = QtWidgets.QLabel(self.frame)
        self.tab.setGeometry(QtCore.QRect(90, 20, 411, 31))
        self.tab.setStyleSheet("font: 87 24pt \"Arial Black\";")
        self.tab.setObjectName("tab")
        self.tubiao = QtWidgets.QLabel(self.frame)
        self.tubiao.setGeometry(QtCore.QRect(20, 10, 61, 51))
        self.tubiao.setStyleSheet("border-image: url(:/images/images/shibie.png);\n"
"background-color: rgb(255, 225, 226);")
        self.tubiao.setText("")
        self.tubiao.setObjectName("tubiao")
        RFID_mode.setCentralWidget(self.centralwidget)

        self.retranslateUi(RFID_mode)
        self.stackedWidget.setCurrentIndex(0)
        self.close.clicked.connect(RFID_mode.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RFID_mode)

    def retranslateUi(self, RFID_mode):
        _translate = QtCore.QCoreApplication.translate
        RFID_mode.setWindowTitle(_translate("RFID_mode", "MainWindow"))
        self.lineEdit_s.setPlaceholderText(_translate("RFID_mode", " Sample size："))
        self.lineEdit_l.setPlaceholderText(_translate("RFID_mode", " Learning rate："))
        self.lineEdit_t.setPlaceholderText(_translate("RFID_mode", " Training cycles："))
        self.label_3.setText(_translate("RFID_mode", "Key parameters"))
        self.label_4.setText(_translate("RFID_mode", "Import training data:"))
        self.pushButton_2.setText(_translate("RFID_mode", "Model generation"))
        self.label_process.setText(_translate("RFID_mode", "Training process"))
        self.pushButton_3.setText(_translate("RFID_mode", "Model prediction"))
        self.label_8.setText(_translate("RFID_mode", "Antenna 1:"))
        self.label_9.setText(_translate("RFID_mode", "Antenna 2:"))
        self.label_10.setText(_translate("RFID_mode", "Antenna 3:"))
        self.label_11.setText(_translate("RFID_mode", "Antenna 4:"))
        self.label_12.setText(_translate("RFID_mode", "Signal strength"))
        self.label_13.setText(_translate("RFID_mode", "Antenna angle"))
        self.label_14.setText(_translate("RFID_mode", "Carrier dissipation"))
        self.pushButton_5.setText(_translate("RFID_mode", "Return to training"))
        self.label_15.setText(_translate("RFID_mode", "Predicted results:"))
        self.label_16.setText(_translate("RFID_mode", "Save"))
        self.label_17.setText(_translate("RFID_mode", "Clear"))
        self.tab.setText(_translate("RFID_mode", "Predictive Models V2.0 "))
import resource_rc
